### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AdvTimber** [p4535992/foundryvtt-item-link-tree#1]
Hey - dunno if this is a bug or not,

when I use the weightless unequip function, the bag registers as 0 in the inventory, but it doesnt remove the weight from the encumbrance bar.

I'm using variant encumbrance 5e, 

they have a encumbered stage at 5xSTR where the player loses 10ft of movement.

player A has a strength of 8 and has the bag equipped with 30lbs of gear in it, plus their staff and focus, spellbook, and coinage; they are at 42lbs.

With Weightless Unequipped checked off, taking off the 30lb backpack (like using an action to remove their pack in combat) should drop them to 12lbs and regain their movement speed to full.

but its not; any ideas?

**Comment by p4535992** [comment]
I'm sorry i think i mixed up some link on my side, for what module did you open this issue ?
