### ISSUE TITLE
[BUG] Cannot open charachter sheet

### ISSUE THREAD

**Issue by alexdiste** [p4535992/foundryvtt-item-link-tree#2]
**Module Version:** v11.0.24

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Foundry 11.315, activating module DAE 11.0.24 on Dnd5e 2.4.0 the character sheet will not open
<img width="287" alt="image" src="https://github.com/p4535992/foundryvtt-item-link-tree/assets/82694721/7f75e15c-e553-4b46-b157-6be9b1160a4e">
This happen in both migrated PC from old world and in new world.
<img width="281" alt="image" src="https://github.com/p4535992/foundryvtt-item-link-tree/assets/82694721/9c4b1916-6251-4353-bc01-5f3c3eadfbaa">

**Foundry Version:**  11.315

**Game System:**  Dnd 2.4.0

**Comment by p4535992** [comment]
This is not the dae issues page O.O
