### ISSUE TITLE
Change the wording of the babonus recommended dependency

### ISSUE THREAD

**Issue by krbz999** [p4535992/foundryvtt-item-link-tree#3]
I just happened to stumble on this, and I'm sure it was just due to copying and pasting, but I would prefer if the readme did not list Build-a-Bonus as doing any sort of wrapping of core or system methods, as that is something it does nothing of and I always strive not to do anything like that in any of my modules.

I would rather not have people think that Build-a-Bonus is in any way, shape, or form a modification on default behavior.

**Comment by p4535992** [comment]
update the readme
