### ISSUE TITLE
D&D 5e 4.0.4 Support

### ISSUE THREAD

**Issue by russcleggvasion** [p4535992/foundryvtt-item-link-tree#4]
Not sure if you're aware yet, but DAE can't be used with the latest D&D 5e system. DAE states it only supports up to version 3.9.99

![image](https://github.com/user-attachments/assets/42abe888-1db9-46c6-8ad0-4586b2024f2c)

**Comment by russcleggvasion** [comment]
Game system info:
![image](https://github.com/user-attachments/assets/7898d25b-f067-4abb-998b-a653b70f1350)

**Comment by russcleggvasion** [comment]
Forgive me if this is the wrong repo. I just saw this is the "Link Tree" repo, but I got here from the "Issue Tracker" link at:
https://gitlab.com/tposney/dae
![image](https://github.com/user-attachments/assets/6aeb769d-5bee-4e9a-bfc3-7c48365b1e73)

**Comment by p4535992** [comment]
no problem
